### ISSUE TITLE
Spawning temporary actors with [ExecuteInEditMode]

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#27] opened 2018-08-30 18:13 UTC
I wrote a little script to spawn a bunch of (temporary) prefab actors. It spawns them `OnEnable` and destroys them `OnDisable`. So far, everything worked beautifully.

However, after adding `[ExecuteInEditMode]` to it, things broke down. It spawned actors without removing them. This might be a bug?

Also, a quick fix is using `[Serialize]`.
```csharp
[ExecuteInEditMode]
public class TenSpawner : Script
{
	public Prefab PrefabToSpawn { get; set; }
	public int Count = 10;
	
        // Quick fix
	// [Serialize]
	private Actor _container;

	private void OnEnable()
	{
		// Safety check
		if (PrefabToSpawn == null) return;
		
		// Create a new container/reuse the existing one
		if (_container == null)
		{
			_container = New<EmptyActor>();
			this.Actor.AddChild(_container, false);
		}
		else
		{
			_container.DestroyChildren();
		}

		// Add a bunch of children to it
		for (int i = 0; i < Count; i++)
		{
			var spawnedActor = PrefabManager.SpawnPrefab(PrefabToSpawn, _container);
		}
	}

	private void OnDisable()
	{
		// Clean up after yourself
		Destroy(_container);
	}
}
```

**Comment by mafiesto4** [comment] 2018-09-06 19:38
Thanks for the report. I was able to reproduce it but the problem is that in `OnDisable` you don't clear the reference to a deleted object and it is left as an invalid reference (object is not null but it does not have a valid pointer to the underlying C++ object).

The proper fix for this would be changing `OnDisable` to:
```cs
Destroy(ref _container);
```

Or you can modify the `OnEnable` and use this check:
```cs
if (!_container) // <- implicit comparision operator that checks if object is not null and has valid C++ object reference
{
...
```

**Closed by mafiesto4** 2018-09-06 19:38 UTC
Labels: bug

**Comment by stefnotch** [comment] 2018-09-17 07:41
I changed `Destroy(_container);` to `Destroy(ref _container);`, however, an issue still persists.
If I repeatedly start and stop the game, it will spawn actors, but not remove them.

Here is what it looks like after hitting `Play` a few times.
![image](https://user-images.githubusercontent.com/10220080/45610862-c125b980-ba5d-11e8-8d8c-030fabd1a583.png)

**Comment by stefnotch** [comment] 2018-09-18 10:30
@mafiesto4 Should I open a new issue or should this issue be re-opened?

**Comment by mafiesto4** [comment] 2018-09-18 12:46
Can you send me a project on Discord? Because I tested with `ref` keyword and it worked well. Maybe my reproduction steps were different.

**Comment by mafiesto4** [comment] 2018-09-19 09:29
Ok I tested your project and I was able to see the issue. 

The problem here is not related to the engine but more to the scene objects usage. Because your script always spawns the object in `Start` (if no reference is saved). So using this quick fix is actually a proper way of usage.

I was thinking about changing the play-mode enter logic from `Serialize Scenes -> OnDisable -> Play` to  `OnDisable -> Serializes Scenes -> Play` but it would break some stuff and we don't want to modify it now.

To fix this you can also use [Actor.HideFlags = HideFlags.DontSave](https://docs.flaxengine.com/api/FlaxEngine.HideFlags.html) which is a good choise for a temporary run-time only objects.

Or use [Actor.GetOrAddChild](https://docs.flaxengine.com/api/FlaxEngine.Actor.html#collapsible-FlaxEngine_Actor_GetOrAddChild__1) to don't spawn actor if it's already there.
